<?php

/*
 * Kategori kapak fotografi ararken kullanilan Ingilizce sorgular.
 *
 * Neden elle yazildi: baslik adini otomatik cevirmek ise yaramiyor.
 * "Kedi Teli ve Guvenlik Filesi" kelime kelime cevrildiginde "cat wire"
 * oluyor ve alakasiz sonuc donuyor; dogrusu "cat balcony safety net".
 * Ayni sekilde "Kaporta ve Boya" -> "body and paint" degil
 * "car body repair shop".
 *
 * Sorgular Wikimedia Commons'a gider. Bir slug burada yoksa komut
 * baslik adindan sozluk temelli bir sorgu uretir; sonuc genelde daha
 * zayiftir, bu yuzden anasayfada gorunen basliklar burada tutulur.
 */

return [
    'queries' => [
        // --- hizmet kokleri (grup baslik gorselleri) ---
        'tadilat-dekorasyon-insaat' => 'home renovation construction interior',
        'montaj-tamir-ve-teknik-servis' => 'technician repairing appliance tools',
        'temizlik-hizmetleri' => 'cleaning service worker house',
        'nakliyat-ve-depolama' => 'moving company truck boxes',
        'ozel-ders-ve-egitim' => 'private tutor teaching student',
        'saglik-guzellik-ve-spor' => 'wellness spa fitness health',
        'dugun-ve-organizasyon' => 'wedding reception celebration',
        'kurumsal-ve-profesyonel-hizmetler' => 'business office professional meeting',
        'oto-ve-arac-hizmetleri' => 'car mechanic auto repair garage',
        'evcil-hayvan-hizmetleri' => 'pet grooming dog care',

        // --- ilan kokleri ---
        'emlak' => 'residential apartment building housing',
        'vasita' => 'used cars dealership',
        'elektronik-teknoloji' => 'consumer electronics devices',
        'yasam-ve-hobi' => 'hobby craft collection',
        'is-makineleri-sanayi' => 'excavator construction machinery',
        'hayvanlar-alemi' => 'domestic animals farm',
        'is-ilanlari-yardimci-arayanlar' => 'job interview hiring office',
        'ustalar-hizmetler' => 'craftsman working tools',

        // --- Tadilat, Dekorasyon ve Insaat ---
        'tadilat-dekorasyon-insaat-boya-badana-siva' => 'painter decorating wall roller',
        'tadilat-dekorasyon-insaat-zemin-duvar-kaplama' => 'laying floor tiles installation',
        'tadilat-dekorasyon-insaat-mutfak-banyo-tadilat' => 'kitchen renovation modern interior',
        'tadilat-dekorasyon-insaat-kapi-pencere' => 'window installation door frame',
        'tadilat-dekorasyon-insaat-cam-balkon-teras-kapatma' => 'glass balcony enclosure terrace',
        'tadilat-dekorasyon-insaat-panjur-sineklik-tente' => 'window awning shutter facade',
        'tadilat-dekorasyon-insaat-alcipan-asma-tavan-kartonpiyer' => 'drywall ceiling installation plasterboard',
        'tadilat-dekorasyon-insaat-cati-dis-cephe-yalitim' => 'roof worker facade insulation',
        'tadilat-dekorasyon-insaat-kaba-insaat-duvar-yikim' => 'bricklayer building wall construction',
        'tadilat-dekorasyon-insaat-mobilya-dolap-marangoz' => 'carpenter workshop woodworking furniture',
        'tadilat-dekorasyon-insaat-doseme-perde-tekstil' => 'curtains upholstery interior textile',
        'tadilat-dekorasyon-insaat-demir-aluminyum-korkuluk' => 'metal railing welding balustrade',
        'tadilat-dekorasyon-insaat-bahce-peyzaj-cit' => 'garden landscaping lawn hedge',
        'tadilat-dekorasyon-insaat-ic-mimari-proje-muhendislik' => 'architect blueprint office plans',
        'tadilat-dekorasyon-insaat-komple-tadilat-yenileme' => 'apartment renovation interior work',
        'tadilat-dekorasyon-insaat-yeni-yapi-prefabrik-havuz' => 'prefabricated house swimming pool construction',
        'tadilat-dekorasyon-insaat-tesisat-dogalgaz-enerji' => 'gas pipe installation plumber boiler',
        'tadilat-dekorasyon-insaat-mermer-granit-dogal-tas' => 'marble slab stone countertop',
        'tadilat-dekorasyon-insaat-cam-filmi-ayna-folyo' => 'window film tinting glass applying',
        'tadilat-dekorasyon-insaat-hurda-moloz-is-makinesi' => 'construction debris container excavator',

        // --- Montaj, Tamir ve Teknik Servis ---
        'montaj-tamir-ve-teknik-servis-kombi-dogalgaz-ve-isitma-sistemleri' => 'gas boiler heating technician',
        'montaj-tamir-ve-teknik-servis-klima-ve-havalandirma' => 'air conditioner installation hvac',
        'montaj-tamir-ve-teknik-servis-beyaz-esya-servisi' => 'repairman washing machine appliance',
        'montaj-tamir-ve-teknik-servis-kucuk-ev-aletleri-tamiri' => 'small appliance repair workshop',
        'montaj-tamir-ve-teknik-servis-elektrik-tesisati-ve-aydinlatma' => 'electrician wiring installation',
        'montaj-tamir-ve-teknik-servis-su-tesisati-sihhi-tesisat-ve-su-aritma' => 'plumber pipes sink installation',
        'montaj-tamir-ve-teknik-servis-tikaniklik-acma-ve-su-kacagi-tespiti' => 'drain cleaning sewer plumber',
        'montaj-tamir-ve-teknik-servis-kapi-kilit-ve-cilingir' => 'locksmith door lock key',
        'montaj-tamir-ve-teknik-servis-pencere-cam-ve-dograma' => 'glazier window glass installation',
        'montaj-tamir-ve-teknik-servis-panjur-kepenk-ve-perde-sistemleri' => 'roller shutter window blinds',
        'montaj-tamir-ve-teknik-servis-mobilya-montaj-ve-tamiri' => 'furniture assembly tools cabinet',
        'montaj-tamir-ve-teknik-servis-tv-uydu-ve-anten-sistemleri' => 'satellite dish antenna roof',
        'montaj-tamir-ve-teknik-servis-bilgisayar-laptop-ve-yazici' => 'computer repair laptop technician',
        'montaj-tamir-ve-teknik-servis-telefon-tablet-ve-elektronik-cihaz-tamiri' => 'smartphone repair workbench',
        'montaj-tamir-ve-teknik-servis-guvenlik-sistemleri-diafon-ve-yangin' => 'security camera cctv installation',
        'montaj-tamir-ve-teknik-servis-internet-kablo-ve-ag-altyapisi' => 'network cabling server rack ethernet',
        'montaj-tamir-ve-teknik-servis-asansor-otomatik-kapi-ve-bina-sistemleri' => 'elevator door building lift',
        'montaj-tamir-ve-teknik-servis-arac-servisi-ve-bakimi' => 'car service garage mechanic',
        'montaj-tamir-ve-teknik-servis-yapi-cati-ve-zemin-tamirati' => 'roof repair worker tiles',
        'montaj-tamir-ve-teknik-servis-ayakkabi-canta-saat-ve-kisisel-esya-tamiri' => 'shoemaker cobbler workshop repair',

        // --- Temizlik Hizmetleri ---
        'temizlik-hizmetleri-ev-ve-daire-temizligi' => 'cleaning vacuum housework home',
        'temizlik-hizmetleri-apartman-site-ve-bina-temizligi' => 'cleaning staircase apartment building',
        'temizlik-hizmetleri-isyeri-ve-ticari-alan-temizligi' => 'office cleaning commercial floor',
        'temizlik-hizmetleri-cam-ve-cephe-temizligi' => 'window cleaner facade squeegee',
        'temizlik-hizmetleri-hali-ve-koltuk-yikama' => 'carpet cleaning service upholstery',
        'temizlik-hizmetleri-tekstil-yorgan-ve-perde-yikama' => 'laundry textile washing blankets',
        'temizlik-hizmetleri-kuru-temizleme-ve-utu' => 'dry cleaning shop ironing',
        'temizlik-hizmetleri-ilaclama-ve-hasere-kontrolu' => 'pest control spraying exterminator',
        'temizlik-hizmetleri-petek-ve-isitma-sistemi-temizligi' => 'radiator heating cleaning maintenance',
        'temizlik-hizmetleri-baca-ve-havalandirma-temizligi' => 'chimney sweep ventilation duct',
        'temizlik-hizmetleri-su-deposu-ve-sebil-temizligi' => 'water tank cleaning tanker',
        'temizlik-hizmetleri-mermer-zemin-ve-yuzey-bakimi' => 'floor polishing machine marble',
        'temizlik-hizmetleri-buharli-temizlik-hizmetleri' => 'steam cleaner cleaning machine',
        'temizlik-hizmetleri-temizlik-makinesi-kiralama' => 'floor scrubber cleaning equipment',
        'temizlik-hizmetleri-arac-temizlik-ve-bakimi' => 'car wash detailing foam',
        'temizlik-hizmetleri-elektronik-cihaz-temizligi' => 'cleaning computer keyboard dust',
        'temizlik-hizmetleri-bahce-ve-dis-alan-temizligi' => 'garden cleaning leaves sweeping',
        'temizlik-hizmetleri-evde-yemek-ve-ascilik' => 'home cooking kitchen chef',

        // --- Nakliyat ve Depolama ---
        'nakliyat-ve-depolama-ev-tasimaciligi' => 'movers carrying furniture boxes',
        'nakliyat-ve-depolama-ofis-ve-isyeri-tasima' => 'moving boxes office relocation',
        'nakliyat-ve-depolama-parca-esya-tasima' => 'refrigerator delivery appliance movers',
        'nakliyat-ve-depolama-uluslararasi-tasimacilik' => 'international freight container truck',
        'nakliyat-ve-depolama-depolama-ve-depo-kiralama' => 'self storage warehouse units',
        'nakliyat-ve-depolama-kamyonet-ve-panelvan-nakliye' => 'delivery van cargo transport',
        'nakliyat-ve-depolama-asansor-ve-vinc-kiralama' => 'furniture lift crane building',
        'nakliyat-ve-depolama-arac-ve-motosiklet-tasima' => 'car transporter trailer vehicle',
        'nakliyat-ve-depolama-oto-cekici-ve-yol-yardimi' => 'tow truck roadside assistance',
        'nakliyat-ve-depolama-kurye-ve-kargo' => 'courier parcel delivery package',
        'nakliyat-ve-depolama-evcil-hayvan-tasima' => 'pet carrier transport dog',
        'nakliyat-ve-depolama-transfer-ve-vip-ulasim' => 'airport transfer minivan chauffeur',
        'nakliyat-ve-depolama-servis-ve-personel-tasimaciligi' => 'shuttle bus passengers minibus',
        'nakliyat-ve-depolama-arac-kiralama-ve-sofor' => 'car rental keys chauffeur',
        'nakliyat-ve-depolama-hurda-ve-moloz-tasima' => 'waste removal skip container',
        'nakliyat-ve-depolama-yuk-ve-lojistik' => 'logistics warehouse forklift pallets',
        'nakliyat-ve-depolama-hamal-ve-yukleme-bosaltma' => 'loading truck workers cargo',

        // --- Ozel Ders ve Egitim ---
        'ozel-ders-ve-egitim-akademik-ozel-ders' => 'tutoring lesson student teacher',
        'ozel-ders-ve-egitim-sinava-hazirlik' => 'exam students classroom desks',
        'ozel-ders-ve-egitim-yabanci-dil-dersleri' => 'language class teacher blackboard',
        'ozel-ders-ve-egitim-egitim-ve-ogrenci-koclugu' => 'counseling student mentor meeting',
        'ozel-ders-ve-egitim-muzik-dersleri' => 'piano lesson guitar teacher',
        'ozel-ders-ve-egitim-dans-dersleri' => 'dance class studio dancers',
        'ozel-ders-ve-egitim-fitness-pilates-ve-yoga' => 'yoga class pilates studio',
        'ozel-ders-ve-egitim-takim-ve-raket-sporlari' => 'tennis coach basketball training',
        'ozel-ders-ve-egitim-yuzme-ve-su-sporlari' => 'swimming lesson pool instructor',
        'ozel-ders-ve-egitim-dovus-sanatlari' => 'martial arts karate training dojo',
        'ozel-ders-ve-egitim-bireysel-ve-doga-sporlari' => 'hiking climbing outdoor sport',
        'ozel-ders-ve-egitim-surucu-kursu-ve-ehliyet' => 'driving school learner instructor',
        'ozel-ders-ve-egitim-ozel-egitim-ve-destek' => 'special education teacher child',
        'ozel-ders-ve-egitim-cocuk-egitimi-ve-etkinlikleri' => 'children classroom activity kindergarten',
        'ozel-ders-ve-egitim-bilisim-ve-yazilim-egitimi' => 'programming class computer students',
        'ozel-ders-ve-egitim-sanat-ve-el-sanatlari' => 'art class painting workshop',
        'ozel-ders-ve-egitim-mutfak-ve-ascilik-egitimi' => 'cooking class chef students',
        'ozel-ders-ve-egitim-guzellik-ve-bakim-egitimleri' => 'beauty training makeup course',
        'ozel-ders-ve-egitim-din-egitimi' => 'quran reading study book',
        'ozel-ders-ve-egitim-kisisel-gelisim-ve-kariyer' => 'seminar presentation audience training',

        // --- Saglik, Guzellik ve Spor ---
        'saglik-guzellik-ve-spor-psikoloji-ve-terapi' => 'psychotherapy counseling session',
        'saglik-guzellik-ve-spor-diyet-ve-beslenme' => 'nutritionist healthy food vegetables',
        'saglik-guzellik-ve-spor-fizik-tedavi-ve-rehabilitasyon' => 'physiotherapy rehabilitation exercise',
        'saglik-guzellik-ve-spor-evde-hasta-ve-yasli-bakimi' => 'elderly care nurse home',
        'saglik-guzellik-ve-spor-kisisel-antrenor-ve-fitness' => 'personal trainer gym workout',
        'saglik-guzellik-ve-spor-pilates-yoga-ve-meditasyon' => 'yoga meditation studio mat',
        'saglik-guzellik-ve-spor-kuafor-sac-ve-tirnak-bakimi' => 'hairdresser salon haircut',
        'saglik-guzellik-ve-spor-cilt-bakimi-makyaj-ve-epilasyon' => 'facial treatment skin care beauty',
        'saglik-guzellik-ve-spor-masaj-ve-spa' => 'massage spa treatment',
        'saglik-guzellik-ve-spor-alternatif-ve-enerji-terapileri' => 'acupuncture needles treatment therapy',
        'saglik-guzellik-ve-spor-kocluk-ve-kisisel-gelisim' => 'coaching conversation office meeting',
        'saglik-guzellik-ve-spor-dil-konusma-ve-gelisim-destegi' => 'speech therapy child teacher',
        'saglik-guzellik-ve-spor-spor-dersleri-ve-brans-antrenorlugu' => 'sports coach training field',
        'saglik-guzellik-ve-spor-hamilelik-dogum-ve-bebek-destegi' => 'pregnancy newborn baby care',

        // --- Dugun ve Organizasyon ---
        'dugun-ve-organizasyon-dugun-nisan-organizasyonu' => 'wedding ceremony bride groom',
        'dugun-ve-organizasyon-evlilik-teklifi' => 'marriage proposal engagement ring',
        'dugun-ve-organizasyon-ozel-gun-organizasyonu' => 'birthday party decoration celebration',
        'dugun-ve-organizasyon-mevlut-ve-dini-toren' => 'religious ceremony gathering mosque',
        'dugun-ve-organizasyon-catering-ve-yemek' => 'catering buffet banquet food',
        'dugun-ve-organizasyon-pasta-tatli-ve-ikramlik' => 'wedding cake dessert table',
        'dugun-ve-organizasyon-muzik-orkestra-ve-dj' => 'dj party live band stage',
        'dugun-ve-organizasyon-sov-animasyon-ve-eglence' => 'entertainment show performance stage',
        'dugun-ve-organizasyon-dugun-fotograf-ve-video' => 'wedding photographer camera couple',
        'dugun-ve-organizasyon-portre-ve-aile-fotografciligi' => 'portrait photography studio family',
        'dugun-ve-organizasyon-ticari-cekim-ve-video-produksiyon' => 'video production camera crew studio',
        'dugun-ve-organizasyon-gelinlik-abiye-ve-damatlik' => 'wedding dress bridal shop',
        'dugun-ve-organizasyon-gelin-arabasi-ve-arac-kiralama' => 'wedding car decorated limousine',
        'dugun-ve-organizasyon-tekne-ve-yat-kiralama' => 'yacht charter boat sea',
        'dugun-ve-organizasyon-mekan-ve-salon' => 'banquet hall event venue',
        'dugun-ve-organizasyon-susleme-balon-ve-cicek' => 'floral decoration balloons event',
        'dugun-ve-organizasyon-ekipman-ve-mobilya-kiralama' => 'event chairs tent rental setup',

        // --- Kurumsal ve Profesyonel Hizmetler ---
        'kurumsal-ve-profesyonel-hizmetler-web-ve-yazilim-gelistirme' => 'software developer code screen',
        'kurumsal-ve-profesyonel-hizmetler-dijital-pazarlama-ve-reklam' => 'digital marketing analytics screen',
        'kurumsal-ve-profesyonel-hizmetler-grafik-ve-marka-tasarimi' => 'graphic designer workspace design',
        'kurumsal-ve-profesyonel-hizmetler-3b-modelleme-render-ve-teknik-cizim' => '3d modeling cad screen render',
        'kurumsal-ve-profesyonel-hizmetler-video-ses-ve-animasyon-produksiyonu' => 'video editing studio audio mixing',
        'kurumsal-ve-profesyonel-hizmetler-matbaa-ve-baski' => 'printing press printshop offset',
        'kurumsal-ve-profesyonel-hizmetler-tabela-ve-dis-mekan-reklam' => 'billboard shop sign signage',
        'kurumsal-ve-profesyonel-hizmetler-icerik-metin-ve-editorluk' => 'writer typing notebook desk',
        'kurumsal-ve-profesyonel-hizmetler-ceviri-ve-tercume' => 'translation dictionary books desk',
        'kurumsal-ve-profesyonel-hizmetler-muhasebe-ve-mali-musavirlik' => 'accountant calculator documents desk',
        'kurumsal-ve-profesyonel-hizmetler-sirket-kurulumu-tescil-ve-dis-ticaret' => 'business contract signing handshake',
        'kurumsal-ve-profesyonel-hizmetler-sigorta-hizmetleri' => 'insurance agent office customer',
        'kurumsal-ve-profesyonel-hizmetler-emlak-ve-gayrimenkul-danismanligi' => 'real estate agent house keys',
        'kurumsal-ve-profesyonel-hizmetler-vize-ve-gocmenlik-danismanligi' => 'passport visa documents travel',
        'kurumsal-ve-profesyonel-hizmetler-is-sagligi-ve-guvenligi' => 'safety helmet workplace inspection',
        'kurumsal-ve-profesyonel-hizmetler-guvenlik-koruma-ve-arastirma' => 'security guard uniform surveillance',
        'kurumsal-ve-profesyonel-hizmetler-site-ve-tesis-yonetimi' => 'facility management building maintenance',
        'kurumsal-ve-profesyonel-hizmetler-tekstil-ve-konfeksiyon-fason-uretim' => 'textile factory sewing machines',
        'kurumsal-ve-profesyonel-hizmetler-endustriyel-fason-imalat-ve-promosyon' => 'factory production line machining',
        'kurumsal-ve-profesyonel-hizmetler-etkinlik-fuar-ve-gecici-personel' => 'trade fair exhibition stand',

        // --- Oto ve Arac Hizmetleri ---
        'oto-ve-arac-hizmetleri-periyodik-bakim' => 'car maintenance oil change garage',
        'oto-ve-arac-hizmetleri-motor-mekanik-tamir' => 'car engine repair mechanic',
        'oto-ve-arac-hizmetleri-sanziman-aktarma-organlari' => 'car transmission gearbox repair',
        'oto-ve-arac-hizmetleri-fren-rot-suspansiyon' => 'brake disc suspension car repair',
        'oto-ve-arac-hizmetleri-lastik-ve-jant' => 'tire change wheel alloy',
        'oto-ve-arac-hizmetleri-kaporta-ve-boya' => 'car body repair paint shop',
        'oto-ve-arac-hizmetleri-oto-cam' => 'windshield replacement car glass',
        'oto-ve-arac-hizmetleri-cam-filmi-kaplama-folyo' => 'car window tinting wrap',
        'oto-ve-arac-hizmetleri-oto-elektrik-elektronik' => 'car electrical diagnostics wiring',
        'oto-ve-arac-hizmetleri-oto-klima' => 'car air conditioning service',
        'oto-ve-arac-hizmetleri-ses-goruntu-multimedya' => 'car audio stereo speakers',
        'oto-ve-arac-hizmetleri-oto-doseme' => 'car interior upholstery seats',
        'oto-ve-arac-hizmetleri-yikama-detayli-temizlik' => 'car wash detailing polishing',
        'oto-ve-arac-hizmetleri-oto-anahtar-cilingir' => 'car key remote locksmith',
        'oto-ve-arac-hizmetleri-lpg-donusum-sistemleri' => 'lpg autogas tank vehicle',
        'oto-ve-arac-hizmetleri-aksesuar-ekipman-montaji' => 'car accessories roof rack installation',
        'oto-ve-arac-hizmetleri-ekspertiz-danismanlik' => 'car inspection diagnostic checking',
        'oto-ve-arac-hizmetleri-motosiklet-servisi' => 'motorcycle repair workshop mechanic',
        'oto-ve-arac-hizmetleri-yedek-parca-tedarik' => 'auto parts shop spare shelves',
        'oto-ve-arac-hizmetleri-yol-yardim-cekici' => 'tow truck breakdown roadside',

        // --- Evcil Hayvan Hizmetleri ---
        'evcil-hayvan-hizmetleri-pet-kuafor-ve-tiras' => 'dog grooming salon clipper',
        'evcil-hayvan-hizmetleri-otel-ve-pansiyon' => 'dog boarding kennel pet hotel',
        'evcil-hayvan-hizmetleri-evde-bakim-ve-gezdirme' => 'dog walker leash park',
        'evcil-hayvan-hizmetleri-veteriner-ve-saglik' => 'veterinarian examining dog clinic',
        'evcil-hayvan-hizmetleri-egitim-ve-davranis' => 'dog training obedience command',
        'evcil-hayvan-hizmetleri-kedi-teli-ve-guvenlik-filesi' => 'cat balcony safety net window',
        'evcil-hayvan-hizmetleri-kulube-kafes-ve-barinak-yapimi' => 'dog house kennel wooden shelter',
        'evcil-hayvan-hizmetleri-akvaryum-ve-terraryum' => 'aquarium fish tank planted',
        'evcil-hayvan-hizmetleri-evcil-hayvan-tasima' => 'pet carrier travel cat dog',
        'evcil-hayvan-hizmetleri-pet-aksesuar-ve-ozel-uretim' => 'pet accessories collar toys shop',
        'evcil-hayvan-hizmetleri-diger-evcil-hayvan-hizmetleri' => 'pets cat dog together',
    ],

    /*
     * Sorgusu olmayan bir baslik icin ad kelimelerini Ingilizce'ye cevirir.
     * Eksiksiz bir sozluk degil, yalnizca son care.
     */
    'fallback_words' => [
        'temizlik' => 'cleaning', 'tamir' => 'repair', 'montaj' => 'installation',
        'servis' => 'service', 'bakim' => 'maintenance', 'ev' => 'home',
        'bahce' => 'garden', 'arac' => 'car', 'oto' => 'car', 'boya' => 'paint',
        'elektrik' => 'electric', 'tesisat' => 'plumbing', 'insaat' => 'construction',
        'tasima' => 'moving', 'nakliyat' => 'moving', 'egitim' => 'education',
        'ders' => 'lesson', 'saglik' => 'health', 'guzellik' => 'beauty',
        'spor' => 'sport', 'dugun' => 'wedding', 'organizasyon' => 'event',
        'hayvan' => 'pet', 'mobilya' => 'furniture', 'cam' => 'glass',
        'kapi' => 'door', 'pencere' => 'window', 'cati' => 'roof',
        'zemin' => 'floor', 'duvar' => 'wall', 'mutfak' => 'kitchen',
        'banyo' => 'bathroom', 'depolama' => 'storage', 'guvenlik' => 'security',
    ],
];
